version: "3.8"

services:

  app:
    container_name: coins_app
    build: .
    command: ./manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/app
    ports:
      - 9000:9000
    restart: always
    environment:
      - DB_NAME=production